CREATE TABLE `bi_t14s` (
  `bi_primary_id` int(11) NOT NULL AUTO_INCREMENT,
  `created_by` int(11) NOT NULL,
  `created_at` date NOT NULL,
  `task_id` int(11) DEFAULT NULL,
  `requirement_received_date` varchar(255) DEFAULT NULL,
  `client_name` varchar(255) DEFAULT NULL,
  `date_of_allocation` varchar(255) DEFAULT NULL,
  `requirement_name` varchar(255) DEFAULT NULL,
  `open_no_of_position` int(11) DEFAULT NULL,
  `jd_received` enum('Yes','No') DEFAULT NULL,
  `experince_range` varchar(255) DEFAULT NULL,
  `relevant_exp` varchar(255) DEFAULT NULL,
  `mandatory_skills` longtext,
  `any_qualification_criteria` varchar(255) DEFAULT NULL,
  `shift_details` varchar(255) DEFAULT NULL,
  `salary_bracket` varchar(255) DEFAULT NULL,
  `job_location` varchar(255) DEFAULT NULL,
  `onsite_opportunity` enum('Yes','No') DEFAULT NULL,
  `does_the_profile_invovle_travelling` enum('Yes','No') DEFAULT NULL,
  `specific_gender_requirement` varchar(255) DEFAULT NULL,
  `process_of_interview` text,
  `requirement_open_since` varchar(255) DEFAULT NULL,
  `type_of_position` enum('Replacement','On Going Project','New Project') DEFAULT NULL,
  `if_new_project` enum('Received','Pipeline') DEFAULT NULL,
  `requirement_status` enum('Open','Closed','Hold') DEFAULT NULL,
  `requirement_close_date` varchar(255) DEFAULT NULL,
  `team_leader` longtext,
  `due_date` varchar(255) DEFAULT NULL,
  `lead_ref_number` varchar(255) DEFAULT NULL,
  `note` text,
  `assign_to` longtext,
  `assign_to_others_1` longtext,
  `assign_to_others_2` longtext,
  `mark_complete_once_all_fulfilled` enum('In Progress','Completed') DEFAULT NULL,
  `Manager` varchar(255) DEFAULT NULL,
  `responsibilities` longtext,
  `search_executed` int(11) DEFAULT '0',
  `past_company` varchar(255) DEFAULT NULL,
  `industry_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`bi_primary_id`),
  KEY `client_name` (`client_name`),
  KEY `team_leader` (`team_leader`(255))
) ENGINE=InnoDB AUTO_INCREMENT=1457 DEFAULT CHARSET=latin1



CREATE TABLE `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `employee_id` varchar(50) DEFAULT NULL,
  `partner_id` int(11) DEFAULT NULL,
  `time_zone_id` int(11) DEFAULT NULL,
  `user_number` varchar(50) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password` varchar(100) DEFAULT NULL,
  `temp_tool_password` varchar(100) DEFAULT NULL,
  `unique_name` varchar(100) DEFAULT NULL,
  `key_value` varchar(100) DEFAULT NULL,
  `role` int(11) DEFAULT NULL,
  `member_type` enum('IN','FR') DEFAULT 'IN' COMMENT 'Inhouse or freelance',
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `address1` varchar(255) DEFAULT NULL,
  `address2` varchar(255) DEFAULT NULL,
  `zip` varchar(20) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `skype_id` varchar(100) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `cellphone` varchar(20) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `registration_date` datetime DEFAULT NULL,
  `last_modified` datetime DEFAULT NULL,
  `current_status` enum('0','1') DEFAULT '0',
  `token` varchar(255) DEFAULT NULL,
  `status` enum('0','1') DEFAULT '0',
  `ref_userid` int(11) DEFAULT NULL,
  `ip` varchar(100) DEFAULT NULL,
  `product_key` varchar(50) DEFAULT NULL,
  `tool_notification` enum('0','1') DEFAULT '1',
  `odesk_username` varchar(100) DEFAULT NULL COMMENT 'whether manager has access of report section',
  `project_report` enum('0','1') DEFAULT '0',
  `timesheet` enum('0','1') DEFAULT '0',
  `attendance` enum('0','1') DEFAULT '0',
  `odesklog` enum('0','1') DEFAULT '0',
  `performance` enum('0','1') DEFAULT '0',
  `client_report` enum('0','1') DEFAULT '0',
  `user_report` enum('0','1') DEFAULT '0',
  `break_time` varchar(100) DEFAULT NULL,
  `register_offline` int(11) DEFAULT '0',
  `webcam` int(11) DEFAULT '0',
  `snap_service` int(11) DEFAULT '1',
  `audio_recording` enum('SILIENT','BUTTONS','PUSH') DEFAULT NULL,
  `cache_duration_in_user_pc` int(11) DEFAULT '0',
  `audio_upload_preference` enum('IMMEDIATE','ONDEMAND') DEFAULT NULL,
  `multi_face_block` int(11) DEFAULT '0',
  `enable_pause_option` int(11) DEFAULT '0',
  `memo_repeate_time` bigint(20) DEFAULT '30',
  `show_project_window` int(11) DEFAULT '1',
  `show_memo_window` int(11) DEFAULT '1',
  `user_auto_login` int(11) DEFAULT '0',
  `show_icon_in_trey` int(11) DEFAULT '1',
  `audio_recording_interval` int(11) DEFAULT '15',
  `allow_remote` tinyint(4) DEFAULT '0',
  `team_users_ids` text,
  `min_frequency` int(11) DEFAULT '0',
  `max_frequency` int(11) DEFAULT '0',
  `driver_frequency` int(11) DEFAULT '0',
  `driver_upload_count` int(11) DEFAULT '0',
  `apptitle_track_interval` int(11) DEFAULT '0',
  `keyboard_mouse_strokes` varchar(25) DEFAULT 'true',
  `tool_tracking_hrs` text,
  `gps_tracking` tinyint(4) DEFAULT '0',
  `last_logged_in` datetime DEFAULT NULL,
  `bi_report` int(11) DEFAULT '0',
  `default_bi_dashboard` int(11) DEFAULT NULL,
  `otp` varchar(6) DEFAULT NULL,
  `shift_hrs` text,
  `custom_redirect` varchar(255) DEFAULT NULL,
  `logon_server` varchar(150) DEFAULT NULL,
  `host_name` varchar(50) DEFAULT NULL,
  `system_last_boot` varchar(255) DEFAULT NULL,
  `ad_domain` varchar(255) DEFAULT NULL,
  `agent_version` varchar(20) DEFAULT NULL,
  `active_user` varchar(255) DEFAULT NULL,
  `os_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `product_key` (`product_key`),
  KEY `status` (`status`),
  KEY `password` (`password`),
  KEY `partner_id` (`partner_id`),
  KEY `employee_id` (`employee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1



CREATE TABLE `module_files` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `module_name` varchar(100) DEFAULT NULL,
  `pagename` varchar(100) DEFAULT NULL,
  `filename` varchar(100) DEFAULT NULL,
  `table_schema` text,
  `custom_form_id` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1



CREATE TABLE `bi_t8s` (
  `bi_primary_id` int(11) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` text,
  `task_id` text,
  `client_name` text,
  `client_industry1` text,
  `client_industry2` text,
  `client_type` text,
  `establishment_year` int(11) DEFAULT NULL,
  `headquarter` text,
  `total_employees_strength` text,
  `city` text,
  `state` text,
  `full_address` text,
  `other_locations` text,
  `linkedin_status` text,
  `current_spoc` text,
  `current_tl` text,
  `Manager` text,
  `assigned_on_date` text,
  `previous_spoc_and_tl` text,
  `previous_spoc_and_tl_date` text,
  `office_boardline_numbers` text,
  `company_head_name` text,
  `company_head_number` text,
  `agreement_status` text,
  `agreement_signed_date` text,
  `agreement_expiry_date` text,
  `agreement_terms` text,
  `internal_recruitment_team_size` text,
  `number_of_vendors` text,
  `detailed_reason_for_being_inactive` text,
  `client_status` text,
  `since_when_client_inactive` text,
  `usp_of_company` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1



CREATE TABLE `workflow_campaigns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campaign_name` varchar(100) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date DEFAULT NULL,
  `status` enum('active','paused','completed','draft') DEFAULT 'active',
  `ref_table_name` varchar(100) DEFAULT NULL,
  `ref_table_id` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1




CREATE TABLE `workflow_registry` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `campaign_id` int(11) NOT NULL,
  `workflow_name` varchar(150) NOT NULL,
  `webhook_url` text,
  `connector_name` varchar(100) NOT NULL,
  `token` varchar(255) DEFAULT NULL,
  `params` json DEFAULT NULL,
  `last_page_fetched` int(11) DEFAULT '0',
  `depth_limit` int(11) DEFAULT '2',
  `interval_minutes` int(11) DEFAULT '30',
  `next_run_at` datetime DEFAULT NULL,
  `last_executed_at` datetime DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `priority` int(11) DEFAULT '5',
  `retry_count` int(11) DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `campaign_id` (`campaign_id`),
  KEY `connector_name` (`connector_name`),
  KEY `idx_workflow_next_run` (`next_run_at`,`is_active`),
  CONSTRAINT `workflow_registry_ibfk_1` FOREIGN KEY (`campaign_id`) REFERENCES `workflow_campaigns` (`id`) ON DELETE CASCADE,
  CONSTRAINT `workflow_registry_ibfk_2` FOREIGN KEY (`connector_name`) REFERENCES `workflow_connectors` (`connector_name`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1



CREATE TABLE `bi_t20s` (
  `bi_primary_id` int(11) NOT NULL AUTO_INCREMENT,
  `created_by` int(11) NOT NULL,
  `created_at` date NOT NULL,
  `task_id` int(11) DEFAULT NULL,
  `campaign_id` int(11) DEFAULT NULL,
  `connection_request` enum('yes','no') DEFAULT NULL,
  `last_message` date DEFAULT NULL,
  `message_counter` int(11) DEFAULT NULL,
  `linkedin_status` enum('Accepted','Pending') DEFAULT NULL,
  `public_identifier` varchar(255) DEFAULT NULL,
  `linkedin_url` text,
  `Full_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `title` text,
  `location` varchar(255) DEFAULT NULL,
  `about` text,
  `open_to_work` varchar(255) DEFAULT NULL,
  `skills` text,
  `current_position` text,
  `previous_position` text,
  `current_company_startdate` varchar(255) DEFAULT NULL,
  `current_company_enddate` varchar(255) DEFAULT NULL,
  `previous_company_startdate` varchar(255) DEFAULT NULL,
  `previous_company_enddate` varchar(255) DEFAULT NULL,
  `experience` varchar(255) DEFAULT NULL,
  `education` text,
  `twitter_username` varchar(255) DEFAULT NULL,
  `source` varchar(255) DEFAULT NULL,
  `github_link` text,
  `review_count` int(11) DEFAULT NULL,
  `url` text,
  `current_company` varchar(255) DEFAULT NULL,
  `previous_company` varchar(255) DEFAULT NULL,
  `md5_link` text,
  `address` text,
  PRIMARY KEY (`bi_primary_id`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=latin1